services:
  - type: web
    name: resume-analyzer
    env: python
    buildCommand: pip install --upgrade pip && pip install --only-binary :all: -r requirements.txt || pip install -r requirements.txt && python init_db.py
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: resume_analyzer_db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false

databases:
  - name: resume_analyzer_db
    plan: free
    databaseName: resume_analyzer
    user: resume_analyzer_user
